### ISSUE TITLE
ArgsException: cassandra is not an implemented source

### ISSUE THREAD

**Issue by 3thinkthendoit** [openzipkin/zipkin-dependencies-hadoop#5] opened 2015-09-09 02:59 UTC
i get the same problem:
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at com.twitter.scalding.Job$.apply(Job.scala:45)
at com.twitter.scalding.Tool.getJob(Tool.scala:46)
at com.twitter.scalding.Tool.run(Tool.scala:66)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
at com.twitter.scalding.Tool$.main(Tool.scala:126)
... 16 more
Caused by: com.twitter.scalding.ArgsException: cassandra is not an implemented source.
at com.twitter.zipkin.aggregate.SpanSourceProvider$.apply(ZipkinAggregateJob.scala:54)
at com.twitter.zipkin.aggregate.ZipkinAggregateJob.(ZipkinAggregateJob.scala:16)
... 25 more

**Comment by adriancole** [comment] 2015-09-14 19:06
dupe of https://github.com/openzipkin/zipkin-dependencies-hadoop/issues/2

**Closed by adriancole** 2015-09-14 19:06 UTC
